### ISSUE TITLE
Vérifier l'existence des noms avant upload

### ISSUE THREAD

**Issue by romainbar** [benprieur/PyCommonist#7]
Vérifier qu'il n'y a pas de noms en double dans l'upload courant (sinon les images sont écrasées).
Vérifier qu'il n'existe pas une image avec le même nom dans Commons avant upload.

**Comment by benprieur** [comment]
Normalement c'est résolu : un contrôle des noms locaux avant import. Pour chaque fichier à importer, on vérifie que le nom n'est pas déjà utilisé sur Wikimedia Commons.
